version: '3'

services:
  djangoapp:
    build: .
    volumes:
      - ./django-project:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media 
    networks:
      - nginx_network
      - spacedb_network
    depends_on:
      - spacedb

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media 
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  spacedb:
    image: mdillon/postgis
    env_file:
      - config/db/spacedb_env
    networks:
      - spacedb_network
    volumes:
      - spacedb_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  spacedb_network:
    driver: bridge

volumes:
  spacedb_volume:
  static_volume:
  media_volume:
